[[UBPF]]
arch = "aarch64"
git-tree-sha1 = "b23f1d1ff42754ea760789c8820598d14a714d2b"
libc = "glibc"
os = "linux"

    [[UBPF.download]]
    sha256 = "c84ae86b10b9f6597d4f381c7b8e3f21abf2556fb0f09f6e85b845478a75fa23"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.aarch64-linux-gnu.tar.gz"
[[UBPF]]
arch = "aarch64"
git-tree-sha1 = "b1e2250c2122ef0f0ffdd7a302f394786b126261"
libc = "musl"
os = "linux"

    [[UBPF.download]]
    sha256 = "c3935b3a354b4dc8acb687536e47c13179f5635e9230b8e677fd123de7f97185"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.aarch64-linux-musl.tar.gz"
[[UBPF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec3a48fc94a9d6bb29c48184984fedbfcf133dc5"
libc = "glibc"
os = "linux"

    [[UBPF.download]]
    sha256 = "cc25f33475871ee73eeafeab9688129d14f3d4b43f41babb57b928c5a6eebc40"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[UBPF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bdae2acc7a29f4aa50fe381d9e231d35ca815ea"
libc = "musl"
os = "linux"

    [[UBPF.download]]
    sha256 = "b25924db5e3e63c1284febe161309694929f33ae6e8048bf724a2e6e1152bf36"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.armv7l-linux-musleabihf.tar.gz"
[[UBPF]]
arch = "i686"
git-tree-sha1 = "6921e87261aae986eb9f11ea6860de2c12c08184"
libc = "glibc"
os = "linux"

    [[UBPF.download]]
    sha256 = "7920a0008102a5ade8cab43783ac302f15ef204b81ce51bd7898c8dcd3958c30"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.i686-linux-gnu.tar.gz"
[[UBPF]]
arch = "i686"
git-tree-sha1 = "b4354fc85059802b40a896135c4fd6c00693ba8a"
libc = "musl"
os = "linux"

    [[UBPF.download]]
    sha256 = "f24a60f93a65cc2436c39df47162795f9af1eee4e9fee7847a10c2138fb9e52d"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.i686-linux-musl.tar.gz"
[[UBPF]]
arch = "powerpc64le"
git-tree-sha1 = "62a91592fcb78ae93746c32cb11c84159cc34079"
libc = "glibc"
os = "linux"

    [[UBPF.download]]
    sha256 = "e9dbed8169f5cdb02ee25cbc5af1bf8d82b071817ad4e4a1c67f0fc300c66b25"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[UBPF]]
arch = "x86_64"
git-tree-sha1 = "b693e0fe21e88954f67856451ac64b33f8db1f18"
libc = "glibc"
os = "linux"

    [[UBPF.download]]
    sha256 = "115334d243d25228a5c6d8887388f70981949b4704e625c29c5b0b2afc9fc0a5"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.x86_64-linux-gnu.tar.gz"
[[UBPF]]
arch = "x86_64"
git-tree-sha1 = "ff582729de7a8adf1c3ee0cd444a4f7783fd2c21"
libc = "musl"
os = "linux"

    [[UBPF.download]]
    sha256 = "ab62dec41af99f469a66fc133ac3774999f032491809488dafe18a1a68a20009"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.x86_64-linux-musl.tar.gz"
[[UBPF]]
arch = "x86_64"
git-tree-sha1 = "23872d7d63afa9dcbae383b5a34686754300ecbc"
os = "freebsd"

    [[UBPF.download]]
    sha256 = "71bb194a1088eccbbb80f504a5f5aa60da77e1fc3624cb36523525653913bc64"
    url = "https://github.com/JuliaBinaryWrappers/UBPF_jll.jl/releases/download/UBPF-v0.0.1+0/UBPF.v0.0.1.x86_64-unknown-freebsd.tar.gz"
